spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luolili/config-repo.git
          username: luoli
          password: luoli1994


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

