spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luolili/config-repo.git
          username: luolili
          password: luoli1994
          basedir: F:\pro\spring-cloud-config-file


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

